package com.dyjs.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dyjs.entity.SysUser;

public interface SysUserDao {
	SysUser getUser(@Param("username") String username,  @Param("password")String password);
	
	
//	 /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
//    long countByExample(SysUserExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
    int updateUserByID(@Param("id") String id, @Param("password") String password, @Param("newPassword") String newPassword);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
//    int deleteByPrimaryKey(String id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
//    int insert(SysUser record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
//    int insertSelective(SysUser record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
	List<SysUser> getAllUser();
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
//    SysUser selectByPrimaryKey(String id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
//    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
//    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
//    int updateByPrimaryKeySelective(SysUser record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table sys_user
//     *
//     * @mbg.generated Mon Oct 30 14:55:12 CST 2017
//     */
//    int updateByPrimaryKey(SysUser record);
}